package com.example.stromblick.network

data class NetworkResponse(
    val Data: List<Data>,
    val AggregateResults: List<Any> = listOf(),
    val Errors: Any? = null,
    val Total: Int = 0,
)

data class Data(
    val AktenzeichenGenehmigung: Any? = null,
    val AnlagenbetreiberId: Int = 0,
    val AnlagenbetreiberMaStRNummer: String = "",
    val AnlagenbetreiberMaskedName: String = "",
    val AnlagenbetreiberName: String = "",
    val AnlagenbetreiberPersonenArt: Int = 0,
    val AnzahlSolarModule: Int = 0,
    val Batterietechnologie: Any? = null,
    val BetriebsStatusId: Int = 0,
    val BetriebsStatusName: String = "",
    val Breitengrad: Any? = null,
//    val Bruttoleistung: Bruttoleistung = Bruttoleistung(),
    val Bundesland: String = "",
    val BundeslandId: Any? = null,
    val DatumLetzteAktualisierung: String = "",
    val EegAnlageMastrNummer: String = "",
    val EegAnlageRegistrierungsdatum: String = "",
    val EegAnlagenschluessel: String = "",
    val EegInbetriebnahmeDatum: String = "",
//    val EegInstallierteLeistung: EegInstallierteLeistung = EegInstallierteLeistung(),
    val EegZuschlag: Any? = null,
    val EinheitName: String = "",
    val EinheitRegistrierungsdatum: String = "",
    val EndgueltigeStilllegungDatum: Any? = null,
    val EnergietraegerId: Int = 0,
    val EnergietraegerName: String = "",
    val Flurstueck: Any? = null,
    val Gemarkung: Any? = null,
    val Gemeinde: String = "",
    val Gemeindeschluessel: String = "",
    val GemeinsamerWechselrichter: Int = 0,
    val GenehmigungDatum: Any? = null,
    val GenehmigungRegistrierungsdatum: Any? = null,
    val Genehmigungbehoerde: Any? = null,
    val GenehmigungsMastrNummer: Any? = null,
    val GeplantesInbetriebsnahmeDatum: Any? = null,
    val Gruppierungsobjekte: String = "",
    val GruppierungsobjekteIds: String = "",
    val HatFlexibilitaetspraemie: Any? = null,
    val HauptausrichtungSolarModule: Int = 0,
    val HauptausrichtungSolarModuleBezeichnung: String = "",
    val HauptbrennstoffId: Any? = null,
    val HauptbrennstoffNamen: Any? = null,
    val HauptneigungswinkelSolarmodule: Int = 0,
    val Hausnummer: Any? = null,
    val HerstellerWindenergieanlage: Any? = null,
    val HerstellerWindenergieanlageBezeichnung: Any? = null,
    val Id: Int = 0,
    val InbetriebnahmeDatum: String = "",
    val IsAnonymisiert: Boolean = false,
    val IsBuergerenergie: Any? = null,
    val IsEinheitNotstromaggregat: Any? = null,
    val IsNBPruefungAbgeschlossen: Int = 0,
    val KraftwerkBlockName: Any? = null,
    val KraftwerkName: Any? = null,
    val KwkAnlageElektrischeLeistung: Any? = null,
    val KwkAnlageInbetriebnahmedatum: Any? = null,
    val KwkAnlageMastrNummer: Any? = null,
    val KwkAnlageRegistrierungsdatum: Any? = null,
    val KwkZuschlag: Any? = null,
    val Laengengrad: Any? = null,
    val LageEinheit: Int = 0,
    val LageEinheitBezeichnung: String = "",
    val LandId: Int = 0,
    val Landkreis: String = "",
    val Leistungsbegrenzung: Int = 0,
    val LokationId: Int = 0,
    val LokationMastrNr: String = "",
    val MaStRNummer: String = "",
    val MieterstromAngemeldet: Any? = null,
    val MigrationseinheitMastrNummer: Any? = null,
    val NabenhoeheWindenergieanlage: Any? = null,
//    val Nettonennleistung: Nettonennleistung = Nettonennleistung(),
    val NetzbetreiberId: String = "",
    val NetzbetreiberMaStRNummer: String = "",
    val NetzbetreiberMaskedNamen: String = "",
    val NetzbetreiberNamen: String = "",
    val NetzbetreiberPersonenArt: String = "",
    val NutzbareSpeicherkapazitaet: Any? = null,
    val NutzungsbereichGebSA: Int = 0,
    val Ort: String = "",
    val Pilotwindanlage: Any? = null,
    val Plz: String = "",
    val Prototypanlage: Any? = null,
    val Regelzone: Any? = null,
    val RotordurchmesserWindenergieanlage: Any? = null,
    val SpannungsebenenId: Any? = null,
    val SpannungsebenenNamen: String = "",
    val SpeicherEinheitMastrNummer: Any? = null,
    val StandortAnonymisiert: String = "",
    val Strasse: Any? = null,
    val SystemStatusId: Int = 0,
    val SystemStatusName: String = "",
    val TechnologieStromerzeugung: Any? = null,
    val TechnologieStromerzeugungId: Any? = null,
    val ThermischeNutzleistung: Any? = null,
    val Typ: Int = 0,
    val Typenbezeichnung: Any? = null,
    val VollTeilEinspeisung: Int = 0,
    val VollTeilEinspeisungBezeichnung: String = "",
    val WasserkraftErtuechtigung: Boolean = false,
    val WindClusterNordseeId: Any? = null,
    val WindClusterOstseeId: Any? = null,
    val WindparkName: Any? = null,
    val Zuschlagsnummern: String = "",
)

data class Bruttoleistung(
    val type: String = "",
    val value: String = "",
)

data class EegInstallierteLeistung(
    val type: String = "",
    val value: String = "",
)

data class Nettonennleistung(
    val type: String = "",
    val value: String = "",
)
